# Generated by Django 5.0.1 on 2024-08-03 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_mcuuid_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationapplication',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(null=True, upload_to='users/pfps/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_list', to='users.userprofile', verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='title',
            field=models.CharField(max_length=32, null=True, verbose_name='Profile Media Title'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
