# Generated by Django 5.0.1 on 2024-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_registrationapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='text',
            field=models.CharField(blank=True, max_length=256, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfps', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signing',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Signing'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
