# Generated by Django 5.0.1 on 2024-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friends',
            new_name='subscriptions',
        ),
    ]
