# Generated by Django 5.0.1 on 2024-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_friends_userprofile_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
    ]
