# Generated by Django 5.0.1 on 2024-11-11 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profilecomment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Award Type')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('picture', models.ImageField(upload_to='awards/', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraward',
            name='award',
        ),
        migrations.AddField(
            model_name='useraward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraward',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.awardtype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
