# Generated by Django 5.0.1 on 2024-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_awardtype_remove_useraward_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardtype',
            name='code',
            field=models.CharField(default='tbd', max_length=64, verbose_name='The Award Type code'),
            preserve_default=False,
        ),
    ]
