# Generated by Django 5.0.1 on 2024-11-15 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_awardtype_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Is seen'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Profile Media Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='users/pfps', verbose_name='Profile picture'),
        ),
    ]
