# Generated by Django 5.0.1 on 2024-11-26 15:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profilecomment',
            managers=[
                ('displayed_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
