# Generated by Django 5.0.1 on 2025-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profilemedia_type_profilemedia_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationapplication',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Not Reviewed'), (1, 'Approved'), (2, 'Denied')], default=0, verbose_name='Application status'),
        ),
    ]
