# Generated by Django 5.0.1 on 2025-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_registrationapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='was_ever_reviewed',
            field=models.BooleanField(default=False, verbose_name='Was the Application ever reviewed?'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Not Reviewed'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Application status'),
        ),
    ]
