# Generated by Django 5.0.1 on 2025-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_registrationapplication_was_ever_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profilecomment',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='identifier',
            field=models.CharField(default='bebra', max_length=128, verbose_name='Identifier'),
            preserve_default=False,
        ),
    ]
