# Generated by Django 5.1.6 on 2025-05-27 08:16

import django.db.models.deletion
import users.helpers.file_uploading
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profilecomment_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemedia',
            name='image',
            field=models.ImageField(upload_to=users.helpers.file_uploading.profile_media_upload, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
    ]
