# Generated by Django 5.1.6 on 2025-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profilemedia_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Text'),
        ),
    ]
