# Generated by Django 5.1.6 on 2025-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Is profile visible'),
        ),
    ]
