# Generated by Django 5.1.6 on 2025-05-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userprofile_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
