# Generated by Django 5.1.6 on 2025-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_visible_userprofile_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signing',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Signature'),
        ),
    ]
