services:
  web:
    build: .
    command: gunicorn ief.wsgi:application --bind 0.0.0.0:8000 --workers 3
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - redis
      - db
    env_file:
      - test.env

  celery-worker:
    build: .
    command: celery -A ief worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - test.env

  celery-beat:
    build: .
    command: celery -A ief beat -S django -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - test.env

  redis:
    image: redis:8
    
  db:
  # Can be used for testing. Should be disabled for hosted DBs.
    image: postgres:15
    restart: unless-stopped
    env_file:
      - test.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_is_ready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:latest

    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: