services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
  celery:
    build: .
    command: celery -A ief worker -l info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=ief.settings
  redis:
    image: redis
    