services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    command: celery -A ief worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A ief beat -S django -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:8
    
  db:
  # Can be used for testing. Should be disabled for hosted DBs.
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_is_ready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres_data: