# Generated by Django 5.0.1 on 2024-11-20 12:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=2048, verbose_name='Text'),
        ),
    ]
