# Generated by Django 5.0.1 on 2024-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_created_at_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like count'),
        ),
    ]
