# Generated by Django 5.0.1 on 2024-11-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogcomment_managers_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
