# Generated by Django 5.0.1 on 2025-02-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogcomment',
            managers=[
            ],
        ),
    ]
