# Generated by Django 5.1.6 on 2025-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Is the message pinned'),
        ),
    ]
