# Generated by Django 5.1.6 on 2025-05-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_adminmessage_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
