# Generated by Django 5.1.6 on 2025-06-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.section', verbose_name='Section'),
        ),
    ]
